window.masterGalleryData = [
  {
    src: "mech-traction-01.jpg",
    figure: "Figure 4.1",
    titleFr: "Préparation des barres de fibre de verre et de basalte",
    titleEn: "Preparation of glass and basalt fiber bars",
    descriptionFr: "Préparation des spécimens de référence en PRFV et PRFB destinés aux essais de traction. Cette étape permet d'organiser les barres par matériau, de vérifier leur état initial et de préparer les zones instrumentées avant la mise en charge.",
    descriptionEn: "Preparation of reference GFRP and BFRP specimens for tensile testing. This step organizes the bars by material, verifies their initial condition and prepares the instrumented zones before loading.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à la traction",
    testTypeEn: "Tensile strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-traction-02.jpg",
    figure: "Figure 4.2",
    titleFr: "Mise en place de l'extensomètre de 200 mm",
    titleEn: "Installation of the 200 mm extensometer",
    descriptionFr: "Installation de l'extensomètre sur la barre composite afin de suivre les déformations longitudinales pendant l'essai de traction et d'obtenir une mesure expérimentale représentative du comportement mécanique.",
    descriptionEn: "Installation of the extensometer on the composite bar to monitor longitudinal strain during tensile testing and obtain a representative experimental measurement of the mechanical behavior.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à la traction",
    testTypeEn: "Tensile strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-01.jpg",
    figure: "Figure 4.3",
    titleFr: "Préparation des spécimens en fibre de basalte et de verre",
    titleEn: "Preparation of basalt and glass fiber specimens",
    descriptionFr: "Préparation des barres en PRFB et PRFV utilisées pour les essais d'arrachement. Les spécimens sont identifiés et préparés afin d'assurer une longueur d'ancrage et des conditions d'essai contrôlées.",
    descriptionEn: "Preparation of BFRP and GFRP bars used for pullout tests. Specimens are identified and prepared to ensure controlled embedment length and testing conditions.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-02.jpg",
    figure: "Figure 4.4(a)",
    titleFr: "Tubes d'acier",
    titleEn: "Steel tubes",
    descriptionFr: "Tubes d'acier utilisés dans la préparation des spécimens d'arrachement. Ils servent à contrôler la zone d'ancrage et à reproduire les conditions prévues dans le protocole expérimental.",
    descriptionEn: "Steel tubes used in the preparation of pullout specimens. They help control the bonded zone and reproduce the conditions defined in the experimental protocol.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-03.jpg",
    figure: "Figure 4.4(b)",
    titleFr: "Ciment expansif",
    titleEn: "Expansive cement",
    descriptionFr: "Utilisation du ciment expansif dans le montage des spécimens afin de stabiliser certaines zones et de contrôler les conditions de transfert d'efforts pendant l'essai d'arrachement.",
    descriptionEn: "Use of expansive cement in the specimen setup to stabilize selected zones and control load-transfer conditions during the pullout test.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-04.jpg",
    figure: "Figure 4.4(c)",
    titleFr: "Dispositif anti-retenue",
    titleEn: "Debonding device",
    descriptionFr: "Dispositif utilisé pour limiter l'adhérence sur une portion de la barre et obtenir une longueur d'ancrage conforme au protocole d'essai d'arrachement.",
    descriptionEn: "Device used to limit bond over a portion of the bar and obtain the embedment length required by the pullout testing protocol.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-05.jpg",
    figure: "Figure 4.4(d)",
    titleFr: "Coulage du béton",
    titleEn: "Concrete casting",
    descriptionFr: "Coulage des blocs de béton autour des barres composites préparées pour les essais d'arrachement. Cette étape assure l'ancrage des spécimens dans une matrice représentative.",
    descriptionEn: "Casting of concrete blocks around the composite bars prepared for pullout testing. This step embeds the specimens in a representative concrete matrix.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-06.jpg",
    figure: "Figure 4.5",
    titleFr: "Blocs de béton pour les essais d'arrachement",
    titleEn: "Concrete blocks for pullout tests",
    descriptionFr: "Blocs de béton préparés pour recevoir les barres en PRF et permettre l'évaluation de l'adhérence barre-béton par essai d'arrachement.",
    descriptionEn: "Concrete blocks prepared to receive FRP bars and evaluate bar-concrete bond behavior through pullout testing.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-07.jpg",
    figure: "Figure 4.6(a)",
    titleFr: "Installation d'un dispositif pour maintenir le bloc de béton",
    titleEn: "Device used to hold the concrete block",
    descriptionFr: "Installation du dispositif de maintien du bloc de béton pendant l'essai d'arrachement afin d'assurer l'alignement de l'échantillon et la stabilité du montage.",
    descriptionEn: "Installation of the device used to hold the concrete block during pullout testing, ensuring specimen alignment and setup stability.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-08.jpg",
    figure: "Figure 4.6(b)",
    titleFr: "Installation du LVDT sur le bloc de béton",
    titleEn: "LVDT installation on the concrete block",
    descriptionFr: "Installation du capteur LVDT pour mesurer les déplacements relatifs pendant l'essai d'arrachement et suivre la réponse expérimentale du système barre-béton.",
    descriptionEn: "Installation of the LVDT sensor to measure relative displacements during pullout testing and monitor the experimental response of the bar-concrete system.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-09.jpg",
    figure: "Figure 4.6(c)",
    titleFr: "Mise en place de l'ensemble de l'échantillon dans la machine MTS",
    titleEn: "Specimen assembly placed in the MTS machine",
    descriptionFr: "Positionnement de l'assemblage complet dans la machine MTS pour appliquer la charge d'arrachement de manière contrôlée et mesurer la performance d'adhérence.",
    descriptionEn: "Positioning of the complete assembly in the MTS machine to apply controlled pullout loading and measure bond performance.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-arrachement-10.jpg",
    figure: "Figure 4.7",
    titleFr: "Blocs de béton après l'arrachement des barres",
    titleEn: "Concrete blocks after bar pullout",
    descriptionFr: "État des blocs de béton après l'extraction des barres. L'observation visuelle aide à interpréter le mode de rupture et la qualité de l'adhérence entre la barre et le béton.",
    descriptionEn: "Condition of the concrete blocks after bar extraction. Visual observation helps interpret the failure mode and the quality of the bond between the bar and concrete.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance à l'arrachement des barres en PRF",
    testTypeEn: "Pullout resistance of FRP bars",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-interlaminaire-01.jpg",
    figure: "Figure 4.9(a)",
    titleFr: "Positionnement de la barre de PRFB sur les lignes tracées",
    titleEn: "BFRP bar positioned on the marked support lines",
    descriptionFr: "Positionnement d'une barre en PRFB sur les lignes de repère des appuis pour l'essai de cisaillement interlaminaire. L'alignement est nécessaire pour obtenir une sollicitation représentative.",
    descriptionEn: "Positioning of a BFRP bar on the marked support lines for the interlaminar shear test. Proper alignment is required to obtain representative loading.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement interlaminaire",
    testTypeEn: "Interlaminar shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-interlaminaire-02.jpg",
    figure: "Figure 4.9(b)",
    titleFr: "Positionnement de la barre de PRFV sur les lignes tracées",
    titleEn: "GFRP bar positioned on the marked support lines",
    descriptionFr: "Positionnement d'une barre en PRFV sur les appuis avant l'essai de cisaillement interlaminaire, selon le même protocole que les barres en PRFB pour permettre la comparaison.",
    descriptionEn: "Positioning of a GFRP bar on the supports before interlaminar shear testing, using the same protocol as BFRP bars to allow comparison.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement interlaminaire",
    testTypeEn: "Interlaminar shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-01.jpg",
    figure: "Figure 4.10(a)",
    titleFr: "Mâchoire hydraulique inférieure",
    titleEn: "Lower hydraulic grip",
    descriptionFr: "Composant inférieur de la machine hydraulique MTS 647 utilisée pour les essais de cisaillement transversal des barres composites.",
    descriptionEn: "Lower component of the MTS 647 hydraulic machine used for transverse shear testing of composite bars.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-02.jpg",
    figure: "Figure 4.10(b)",
    titleFr: "Mâchoire hydraulique supérieure",
    titleEn: "Upper hydraulic grip",
    descriptionFr: "Composant supérieur de la machine hydraulique utilisé pour appliquer l'effort de cisaillement transversal sur les barres en PRF.",
    descriptionEn: "Upper hydraulic component used to apply transverse shear loading on FRP bars.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-03.jpg",
    figure: "Figure 4.10(c)",
    titleFr: "Machine hydraulique MTS 647",
    titleEn: "MTS 647 hydraulic machine",
    descriptionFr: "Vue d'ensemble de la machine hydraulique MTS 647 conçue pour appliquer une charge contrôlée lors des essais de cisaillement transversal.",
    descriptionEn: "Overall view of the MTS 647 hydraulic machine designed to apply controlled loading during transverse shear tests.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-04.jpg",
    figure: "Figure 4.11(a)",
    titleFr: "Mise en place de la barre sur les deux lames inférieures",
    titleEn: "Bar placed on the two lower blades",
    descriptionFr: "Mise en place de la barre composite sur les deux lames inférieures du dispositif utilisé pour l'essai de cisaillement transversal.",
    descriptionEn: "Placement of the composite bar on the two lower blades of the device used for transverse shear testing.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-05.jpg",
    figure: "Figure 4.11(b)",
    titleFr: "Fixation de la barre avec les vis",
    titleEn: "Bar fixed with screws",
    descriptionFr: "Fixation de la barre à l'aide de vis afin de stabiliser le spécimen avant la descente de la lame supérieure et le lancement de l'essai.",
    descriptionEn: "Fixing of the bar with screws to stabilize the specimen before lowering the upper blade and starting the test.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-cisaillement-transversal-06.jpg",
    figure: "Figure 4.11(c)",
    titleFr: "Descente de la lame supérieure sur la barre",
    titleEn: "Upper blade lowered onto the bar",
    descriptionFr: "Descente progressive de la lame supérieure sur la barre afin d'appliquer la sollicitation de cisaillement transversal dans le dispositif expérimental.",
    descriptionEn: "Progressive lowering of the upper blade onto the bar to apply transverse shear loading within the experimental device.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance au cisaillement transversal",
    testTypeEn: "Transverse shear strength",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-alcalins-01.jpg",
    figure: "Figure 4.12",
    titleFr: "Mise en place des barres PRF dans le bassin de conditionnement alcalin",
    titleEn: "FRP bars placed in the alkaline conditioning tank",
    descriptionFr: "Mise en place des barres en PRF dans un bassin de conditionnement alcalin pour étudier l'effet d'un environnement agressif sur la durabilité des matériaux composites.",
    descriptionEn: "Placement of FRP bars in an alkaline conditioning tank to study the effect of an aggressive environment on the durability of composite materials.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance aux alcalins",
    testTypeEn: "Alkaline resistance",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "mech-alcalins-charge-01.jpg",
    figure: "Figure 4.13",
    titleFr: "Dispositif de conditionnement des spécimens soumis à une charge",
    titleEn: "Conditioning device for loaded specimens",
    descriptionFr: "Dispositif permettant de maintenir une charge sur les spécimens pendant le conditionnement alcalin afin d'évaluer l'effet combiné de l'environnement et de la sollicitation mécanique.",
    descriptionEn: "Device used to maintain load on specimens during alkaline conditioning in order to evaluate the combined effect of environment and mechanical stress.",
    category: "Essais de propriétés mécaniques",
    categoryEn: "Mechanical property tests",
    testType: "Résistance aux alcalins avec charges",
    testTypeEn: "Alkaline resistance with sustained loads",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-section-effective-01.jpg",
    figure: "Figure 4.14(a)",
    titleFr: "Longueur du spécimen",
    titleEn: "Specimen length",
    descriptionFr: "Mesure de la longueur du spécimen utilisée dans la détermination de la section effective des barres composites.",
    descriptionEn: "Measurement of specimen length used in determining the effective cross-sectional area of composite bars.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Section effective",
    testTypeEn: "Effective area",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-section-effective-02.jpg",
    figure: "Figure 4.14(b)",
    titleFr: "Poids du spécimen sec",
    titleEn: "Dry specimen weight",
    descriptionFr: "Mesure de la masse sèche du spécimen avant immersion, utilisée dans le calcul de la section effective.",
    descriptionEn: "Measurement of the dry specimen mass before immersion, used in the calculation of effective area.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Section effective",
    testTypeEn: "Effective area",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-section-effective-03.jpg",
    figure: "Figure 4.14(c)",
    titleFr: "Poids du spécimen dans l'eau",
    titleEn: "Specimen weight in water",
    descriptionFr: "Pesée hydrostatique du spécimen dans l'eau afin d'obtenir les données nécessaires au calcul de la section effective.",
    descriptionEn: "Hydrostatic weighing of the specimen in water to obtain the data required for calculating effective area.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Section effective",
    testTypeEn: "Effective area",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-section-effective-04.jpg",
    figure: "Figure 4.14(d)",
    titleFr: "Poids du récipient avec l'eau",
    titleEn: "Container weight with water",
    descriptionFr: "Mesure de référence du récipient contenant l'eau, utilisée dans la procédure de détermination de la section effective.",
    descriptionEn: "Reference measurement of the container with water, used in the effective area determination procedure.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Section effective",
    testTypeEn: "Effective area",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-01.jpg",
    figure: "Figure 4.15(a)",
    titleFr: "Barres en PRFV sablées",
    titleEn: "Sanded GFRP bars",
    descriptionFr: "Échantillons de barres en PRFV sablées utilisés pour l'essai de teneur en fibres et l'évaluation de la composition du matériau composite.",
    descriptionEn: "Sanded GFRP bar samples used for fiber content testing and evaluation of the composite material composition.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-02.jpg",
    figure: "Figure 4.15(b)",
    titleFr: "Barres en PRFB sablées",
    titleEn: "Sanded BFRP bars",
    descriptionFr: "Échantillons de barres en PRFB sablées préparés pour caractériser la proportion de fibres, de résine et de sable.",
    descriptionEn: "Sanded BFRP bar samples prepared to characterize the proportion of fibers, resin and sand.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-03.jpg",
    figure: "Figure 4.15(c)",
    titleFr: "Barres en PRFB non sablées",
    titleEn: "Non-sanded BFRP bars",
    descriptionFr: "Échantillons de barres en PRFB non sablées utilisés pour comparer la composition du matériau avec celle des barres sablées.",
    descriptionEn: "Non-sanded BFRP bar samples used to compare material composition with sanded bars.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-04.jpg",
    figure: "Figure 4.16(a)",
    titleFr: "Poids du contenant vide",
    titleEn: "Empty container weight",
    descriptionFr: "Pesée du contenant vide avant l'essai de teneur en fibres afin d'établir la référence de masse utilisée dans les calculs.",
    descriptionEn: "Weighing of the empty container before the fiber content test to establish the reference mass used in calculations.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-05.jpg",
    figure: "Figure 4.16(b)",
    titleFr: "Poids du spécimen, fibres et résine",
    titleEn: "Specimen weight, fibers and resin",
    descriptionFr: "Pesée du spécimen avant séparation des constituants pour déterminer la proportion de fibres et de résine dans le matériau composite.",
    descriptionEn: "Weighing of the specimen before separation of constituents to determine the proportion of fibers and resin in the composite material.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-06.jpg",
    figure: "Figure 4.16(c)",
    titleFr: "Poids des résidus, fibres et sable",
    titleEn: "Residue weight, fibers and sand",
    descriptionFr: "Pesée des résidus après traitement, comprenant les fibres et le sable, pour compléter le bilan de masse de l'essai de teneur en fibres.",
    descriptionEn: "Weighing of residues after treatment, including fibers and sand, to complete the mass balance of the fiber content test.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-teneur-fibres-07.jpg",
    figure: "Figure 4.16(d)",
    titleFr: "Poids du sable",
    titleEn: "Sand weight",
    descriptionFr: "Mesure du poids du sable récupéré afin de distinguer les constituants dans l'analyse de la teneur en fibres des barres sablées.",
    descriptionEn: "Measurement of recovered sand weight to distinguish constituents in the fiber content analysis of sanded bars.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Teneur en fibres",
    testTypeEn: "Fiber content",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-absorption-humidite-01.jpg",
    figure: "Figure 4.17(a)",
    titleFr: "Barres non sablées",
    titleEn: "Non-sanded bars",
    descriptionFr: "Barres non sablées utilisées dans la détermination du taux d'absorption d'humidité des matériaux composites.",
    descriptionEn: "Non-sanded bars used to determine the moisture absorption rate of composite materials.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Taux d'absorption d'humidité",
    testTypeEn: "Moisture absorption rate",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-absorption-humidite-02.jpg",
    figure: "Figure 4.17(b)",
    titleFr: "Taille du spécimen",
    titleEn: "Specimen size",
    descriptionFr: "Mesure des dimensions du spécimen afin de documenter la géométrie utilisée dans l'essai d'absorption d'humidité.",
    descriptionEn: "Measurement of specimen dimensions to document the geometry used in the moisture absorption test.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Taux d'absorption d'humidité",
    testTypeEn: "Moisture absorption rate",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-absorption-humidite-03.jpg",
    figure: "Figure 4.17(c)",
    titleFr: "Température du four",
    titleEn: "Oven temperature",
    descriptionFr: "Contrôle de la température du four pendant le séchage des spécimens, étape nécessaire à la détermination du taux d'absorption d'humidité.",
    descriptionEn: "Control of oven temperature during specimen drying, a required step for determining the moisture absorption rate.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Taux d'absorption d'humidité",
    testTypeEn: "Moisture absorption rate",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-transition-vitreuse-01.jpg",
    figure: "Figure 4.18(a)",
    titleFr: "Spécimen composite préparé pour l'essai DSC",
    titleEn: "Composite specimen prepared for the DSC test",
    descriptionFr: "Préparation d'un spécimen composite destiné à l'analyse DSC pour déterminer la température de transition vitreuse du matériau.",
    descriptionEn: "Preparation of a composite specimen for DSC analysis to determine the glass transition temperature of the material.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Température de transition vitreuse",
    testTypeEn: "Glass transition temperature",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-transition-vitreuse-02.jpg",
    figure: "Figure 4.18(b)",
    titleFr: "Mesure de la masse du spécimen",
    titleEn: "Specimen mass measurement",
    descriptionFr: "Mesure de la masse du spécimen avant l'analyse DSC pour respecter la procédure expérimentale et assurer la traçabilité de l'essai.",
    descriptionEn: "Measurement of specimen mass before DSC analysis to follow the experimental procedure and ensure test traceability.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Température de transition vitreuse",
    testTypeEn: "Glass transition temperature",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-transition-vitreuse-03.jpg",
    figure: "Figure 4.18(c)",
    titleFr: "Positionnement du spécimen dans l'appareil DSC",
    titleEn: "Specimen positioned in the DSC device",
    descriptionFr: "Positionnement du spécimen dans l'appareil DSC utilisé pour la détermination de la température de transition vitreuse.",
    descriptionEn: "Positioning of the specimen in the DSC device used to determine the glass transition temperature.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Température de transition vitreuse",
    testTypeEn: "Glass transition temperature",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-meb-01.jpg",
    figure: "Figure 4.22(a)",
    titleFr: "Découpe des échantillons",
    titleEn: "Sample cutting",
    descriptionFr: "Découpe des échantillons avant l'observation au microscope électronique à balayage, afin d'obtenir des surfaces représentatives du matériau composite.",
    descriptionEn: "Cutting of samples before scanning electron microscope observation to obtain representative surfaces of the composite material.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Microscope électronique à balayage (MEB)",
    testTypeEn: "Scanning electron microscope (SEM)",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-meb-02.jpg",
    figure: "Figure 4.22(b)",
    titleFr: "Enrobage dans la résine",
    titleEn: "Embedding in resin",
    descriptionFr: "Enrobage des échantillons dans la résine pour faciliter la manipulation, le maintien et la préparation de surface avant l'analyse MEB.",
    descriptionEn: "Embedding of samples in resin to facilitate handling, holding and surface preparation before SEM analysis.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Microscope électronique à balayage (MEB)",
    testTypeEn: "Scanning electron microscope (SEM)",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-meb-03.jpg",
    figure: "Figure 4.22(c)",
    titleFr: "Meulage initial",
    titleEn: "Initial grinding",
    descriptionFr: "Meulage initial des échantillons afin d'obtenir une surface régulière avant les étapes de polissage et de métallisation.",
    descriptionEn: "Initial grinding of samples to obtain a regular surface before polishing and coating steps.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Microscope électronique à balayage (MEB)",
    testTypeEn: "Scanning electron microscope (SEM)",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-meb-04.jpg",
    figure: "Figure 4.22(d)",
    titleFr: "Polissage",
    titleEn: "Polishing",
    descriptionFr: "Polissage des échantillons pour améliorer la qualité de surface et permettre une observation plus claire de la microstructure.",
    descriptionEn: "Polishing of samples to improve surface quality and allow clearer observation of the microstructure.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Microscope électronique à balayage (MEB)",
    testTypeEn: "Scanning electron microscope (SEM)",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  },
  {
    src: "phys-meb-05.jpg",
    figure: "Figure 4.22(e)",
    titleFr: "Métallisation",
    titleEn: "Coating",
    descriptionFr: "Métallisation des échantillons avant l'observation au microscope électronique à balayage afin d'améliorer la conductivité de surface et la qualité d'imagerie.",
    descriptionEn: "Coating of samples before scanning electron microscope observation to improve surface conductivity and imaging quality.",
    category: "Essais de propriétés physiques",
    categoryEn: "Physical property tests",
    testType: "Microscope électronique à balayage (MEB)",
    testTypeEn: "Scanning electron microscope (SEM)",
    source: "Mémoire de maîtrise, chapitre 4 - Programme expérimental"
  }
];


